import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";

const SYSTEM_PROMPT = `You are a commercial risk identification assistant for small UK construction firms and freelancers (under 25 employees). You analyse construction subcontracts under English law only, focusing on the Housing Grants, Construction and Regeneration Act 1996 (Construction Act) and common patterns in JCT, NEC and bespoke subcontracts used in England.

Your only job is to identify the most common contractual payment traps that cause late or reduced payment. For each issue found:

1. Quote or paraphrase the relevant clause.
2. Explain in plain English why it creates cash-flow risk for a small firm.
3. Give a ready-to-copy suggested commercial amendment the user can paste into an email or mark-up.
4. Rank impact High / Medium / Low using the user’s context (trade, size, duration, role).

Check these issues in priority order:
1. Pay-when-paid / pay-if-paid language
2. Extended or vague payment cycles
3. Retention percentage and release triggers (especially if tied to main works rather than the user’s package)
4. Weak or one-sided notice obligations
5. Broad set-off rights
6. Unfair flow-down / back-to-back clauses
7. Uncapped or excessive liquidated damages
8. Harsh conditions precedent on claims
9. Weak suspension rights on non-payment
10. Vague valuation language

Strict rules:
- English law and Construction Act only.
- You are not a solicitor. Never give legal advice.
- Do NOT repeat a long disclaimer at the start. The website already shows one. Start directly with “Project context used”.
- Use British English spelling throughout (organisation, favour, etc.).
- Keep language simple — the user may be reading on a phone on site.
- Suggested amendments must be commercial negotiation language, not formal legal drafting.
- End with a short “Overall summary” that clearly states the main risks and what to prioritise.

Output format:

Project context used
[summarise trade, size, duration, role and any extra notes]

Risk Register – Payment Traps

### 1. [Issue name] – High/Medium/Low
Where it appears: ...
Why it matters for you: ...
Suggested commercial wording you can copy:
> [ready-to-paste text]

(continue for each relevant issue)

Overall summary
[3–5 sentences focusing on the biggest cash-flow risks and what the user should prioritise in negotiation. End by reminding that this is commercial risk identification only, not legal advice.]
`;

export async function POST(req: NextRequest) {
  try {
    const { context, contractText } = await req.json();

    if (!context || !contractText) {
      return NextResponse.json({ error: "Missing context or contract text" }, { status: 400 });
    }

    const apiKey = process.env.ANTHROPIC_API_KEY;
    if (!apiKey) {
      return NextResponse.json(
        { error: "ANTHROPIC_API_KEY is not set. Add it in Vercel Environment Variables." },
        { status: 500 }
      );
    }

    const anthropic = new Anthropic({ apiKey });

    const userMessage = `User context:\nTrade: ${context.trade}\nProject size: ${context.projectSize}\nDuration: ${context.duration}\nRole: ${context.role}\nExtra: ${context.extra || "none"}\n\nContract text:\n${contractText.slice(0, 100000)}`;

    const message = await anthropic.messages.create({
      model: "claude-sonnet-5",
      max_tokens: 4000,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userMessage }]
    });

    let result = "";
    if (Array.isArray(message.content)) {
      for (const block of message.content) {
        if (block.type === "text" && typeof block.text === "string") {
          result += block.text;
        }
      }
    }

    if (!result) {
      result = "No text response was generated by the model. Please try again.";
    }

    return NextResponse.json({ result });
  } catch (error: any) {
    console.error("Review error:", error);
    return NextResponse.json(
      { error: error.message || "Review failed" },
      { status: 500 }
    );
  }
}