"use client";

import { useState, type ReactNode } from "react";

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <button
      type="button"
      className="shrink-0 text-xs font-semibold text-blue-600 border border-blue-200 rounded-lg px-2 py-1 hover:bg-blue-50"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(text);
          setCopied(true);
          setTimeout(() => setCopied(false), 1500);
        } catch {
          /* ignore */
        }
      }}
    >
      {copied ? "Copied" : "Copy"}
    </button>
  );
}

/** Render review markdown with copy buttons on suggested-wording blockquotes */
export default function ReviewResults({ result }: { result: string }) {
  const lines = result.split("\n");
  const nodes: ReactNode[] = [];
  let i = 0;
  let key = 0;

  while (i < lines.length) {
    const line = lines[i];

    if (/^\*\*Suggested wording:\*\*/i.test(line) || /^Suggested wording:/i.test(line)) {
      nodes.push(
        <p key={key++} className="font-semibold text-gray-900 mt-3 mb-1">
          Suggested wording
        </p>
      );
      i++;
      const quoteLines: string[] = [];
      while (i < lines.length && (lines[i].startsWith(">") || lines[i].trim() === "")) {
        if (lines[i].startsWith(">")) {
          quoteLines.push(lines[i].replace(/^>\s?/, ""));
        } else if (quoteLines.length) {
          break;
        }
        i++;
      }
      const quote = quoteLines.join("\n").trim();
      if (quote) {
        nodes.push(
          <div
            key={key++}
            className="bg-blue-50 border border-blue-100 rounded-xl p-3 my-2 flex gap-2 items-start"
          >
            <p className="text-sm text-gray-800 flex-1 whitespace-pre-wrap leading-relaxed">{quote}</p>
            <CopyButton text={quote} />
          </div>
        );
      }
      continue;
    }

    if (line.startsWith("### ")) {
      nodes.push(
        <h3 key={key++} className="text-base font-bold text-gray-900 mt-5 mb-2">
          {line.replace(/^###\s*/, "")}
        </h3>
      );
      i++;
      continue;
    }

    if (line.startsWith("## ")) {
      nodes.push(
        <h2 key={key++} className="text-lg font-bold text-gray-900 mt-6 mb-2">
          {line.replace(/^##\s*/, "")}
        </h2>
      );
      i++;
      continue;
    }

    if (line.startsWith("---")) {
      nodes.push(<hr key={key++} className="my-4 border-gray-200" />);
      i++;
      continue;
    }

    if (line.trim() === "") {
      i++;
      continue;
    }

    if (/\*\*(.+?)\*\*/.test(line)) {
      const parts = line.split(/(\*\*.+?\*\*)/g);
      nodes.push(
        <p key={key++} className="text-sm text-gray-800 leading-relaxed my-1">
          {parts.map((part, idx) =>
            part.startsWith("**") && part.endsWith("**") ? (
              <strong key={idx}>{part.slice(2, -2)}</strong>
            ) : (
              <span key={idx}>{part}</span>
            )
          )}
        </p>
      );
    } else {
      nodes.push(
        <p key={key++} className="text-sm text-gray-800 leading-relaxed my-1 whitespace-pre-wrap">
          {line}
        </p>
      );
    }
    i++;
  }

  return (
    <div className="space-y-1">
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-xs text-amber-950 mb-4">
        <p className="font-semibold">Automated AI summary</p>
        <p className="mt-0.5">
          This output was generated by artificial intelligence. It is a commercial risk aid only — not legal advice.
          It may be incomplete or incorrect. Have important decisions checked by a qualified professional.
        </p>
      </div>
      {nodes}
    </div>
  );
}
