import Link from "next/link";

export const metadata = {
  title: "Terms of Use — GuardConstruct",
  description: "Terms of use for GuardConstruct."
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FAFAF9] text-gray-900">
      <header className="border-b bg-white">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="font-bold">
            Guard<span className="text-blue-600">Construct</span>
          </Link>
          <Link href="/" className="text-sm text-blue-600">
            Back to app
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-4 py-10 prose prose-sm prose-gray">
        <h1 className="text-3xl font-bold mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: 29 September 2026 · England &amp; Wales</p>

        <h2 className="text-lg font-bold mt-8 mb-2">1. The service</h2>
        <p>
          GuardConstruct provides an <strong>automated commercial risk summary</strong> of construction-related
          documents you upload. It is a software tool for cash-flow awareness. It is{" "}
          <strong>not a law firm</strong>, does not provide regulated legal advice, and does not create a
          solicitor–client relationship.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">2. No legal advice</h2>
        <p>
          Output is generated by artificial intelligence and may be incomplete, outdated or wrong. You must not rely
          on it as legal advice. For decisions with legal or financial consequences, consult a qualified solicitor or
          other professional. Suggested wording is illustrative only.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">3. Eligibility</h2>
        <p>
          You must be 18 or over and using the service for a business or trade. You confirm you have the right to
          upload any document you submit.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">4. Accounts and free tier</h2>
        <p>
          You are responsible for activity under your account. The free tier is limited (including one free check per
          account as presented in the product). We may change limits, refuse service, or suspend abuse.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">5. Subscriptions and cancellation</h2>
        <p>
          Pro is billed via Stripe at the price shown at checkout (currently £19/month unless stated otherwise). You
          can manage or cancel your subscription through the <strong>Manage billing</strong> link in your profile
          (Stripe Customer Portal) or via Stripe&apos;s receipts. Cancellation stops future renewals; charges already
          taken are handled under Stripe&apos;s and applicable consumer rules.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">6. Acceptable use</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>No unlawful content, malware, or attempts to probe or overload the service.</li>
          <li>No uploading of others&apos; confidential documents without authority.</li>
          <li>No resale of output as regulated legal advice.</li>
        </ul>

        <h2 className="text-lg font-bold mt-8 mb-2">7. Intellectual property</h2>
        <p>
          You retain rights in documents you upload. We need a limited licence to process them to provide the
          service. Our branding, site and software remain ours.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">8. Liability</h2>
        <p>
          The service is provided &quot;as is&quot;. To the fullest extent permitted by law we exclude liability for
          loss of profit, contracts, data or indirect loss arising from use of the tool or reliance on its output.
          Nothing excludes liability for death or personal injury caused by negligence, fraud, or other liability that
          cannot be limited under English law. Our total liability for any claim is limited to the greater of £50 or
          the fees you paid us in the 3 months before the claim.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">9. Report a problem</h2>
        <p>
          Copyright or other concerns:{" "}
          <a className="text-blue-600" href="mailto:tobyburrows1@icloud.com">
            tobyburrows1@icloud.com
          </a>
          .
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">10. Law</h2>
        <p>These terms are governed by the laws of England and Wales. Courts of England and Wales have jurisdiction.</p>
      </main>
    </div>
  );
}
