import Link from "next/link";

export const metadata = {
  title: "Terms of Use — GuardConstruct",
  description: "Terms of use for GuardConstruct."
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#FAFAF9] text-gray-900">
      <header className="border-b bg-white">
        <div className="max-w-3xl mx-auto px-4 h-14 flex items-center justify-between">
          <Link href="/" className="font-bold">
            Guard<span className="text-blue-600">Construct</span>
          </Link>
          <Link href="/" className="text-sm text-blue-600">
            Back to app
          </Link>
        </div>
      </header>
      <main className="max-w-3xl mx-auto px-4 py-10 prose prose-sm prose-gray">
        <h1 className="text-3xl font-bold mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-500 mb-8">Last updated: 30 September 2026 · England &amp; Wales</p>

        <h2 className="text-lg font-bold mt-8 mb-2">1. The service</h2>
        <p>
          GuardConstruct provides an <strong>automated commercial risk summary</strong> of construction-related
          documents you upload. It is a software tool for cash-flow awareness. It is{" "}
          <strong>not a law firm</strong>, does not provide regulated legal advice, and does not create a
          solicitor–client relationship.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">2. No legal advice</h2>
        <p>
          Output is generated by artificial intelligence and may be incomplete, outdated or wrong. You must not rely
          on it as legal advice. For decisions with legal or financial consequences, consult a qualified solicitor or
          other professional. Suggested wording is illustrative only.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">3. Eligibility</h2>
        <p>
          You must be 18 or over and using the service for a business or trade. You confirm you have the right to
          upload any document you submit.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">4. Accounts and free tier</h2>
        <p>
          You are responsible for activity under your account. The free tier is limited to the number of free checks
          shown on our pricing page, per person. Email aliases of the same inbox count as one person. Free checks are
          also limited per network per day, and we may pause free checks for everyone on a given day to protect the
          service. We may change limits, refuse service, or suspend abuse.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">4A. Team workspaces (when available)</h2>
        <p>
          You can create a team workspace and invite people by email. The person who creates it (the owner) is responsible
          for its membership and billing. Everyone in a team can see the reviews and tracked deadlines created in it, and
          these stay with the team if someone leaves or is removed. Pro in a team is bought per seat; seats go to the owner
          first and then to members in the order they joined. Members without a seat use their own free allowance.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">5. Subscriptions and cancellation</h2>
        <p>
          Pro is billed via Stripe at the price shown at checkout (currently £19/month unless stated otherwise). Pro
          includes unlimited checks, subject to fair-use rate limits that stop automated or abusive use. You
          can manage or cancel your subscription through the <strong>Manage billing</strong> link in your profile
          (Stripe Customer Portal) or via Stripe&apos;s receipts. Cancellation stops future renewals; charges already
          taken are handled under Stripe&apos;s and applicable consumer rules.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">5A. Your review history</h2>
        <p>
          We keep the results of your checks in your account so you can return to them. Pro accounts can see all of
          them; free accounts can see their latest. You can delete any review you can see at any time, and ask us to
          delete the rest. We don&apos;t keep the files you upload. See the Privacy Policy for what is stored and for how long.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">5B. Project tracking and deadline reminders</h2>
        <p>
          <strong>Reminders are a prompt only. Check your contract for exact dates.</strong> With Pro, you can track
          projects and dates, and GuardConstruct can pick notice and payment deadlines out of a contract and email you
          7 days before, 2 days before, on the day and when a date has passed. Deadlines are identified by AI and <strong>may be wrong, incomplete or missing</strong>. Dates depend on
          information you give us (such as when an event happened) and on how we count days, which we explain in the
          app. You must check each deadline against the contract yourself. Reminders are a convenience only: we don&apos;t
          guarantee that any reminder will be sent, arrive, or arrive on time, and you remain responsible for meeting
          your contractual deadlines. The limits in section 8 apply.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">5C. Help getting paid and referral fees</h2>
        <p>
          If you use <strong>Need help getting paid?</strong>, you send us details of money you say you are owed. If you
          tick the consent box, we may introduce you to a solicitor or adjudication service. <strong>They may pay us a
          referral fee</strong> for that introduction. We will not pass on your request without that consent, and we
          don&apos;t pass anything on automatically. You don&apos;t have to use anyone we suggest; agree any fees directly with
          them. Partners are independent of us and are
          responsible for their own advice and services. We don&apos;t give legal advice about your claim and can&apos;t
          promise any outcome.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">6. Acceptable use</h2>
        <ul className="list-disc pl-5 space-y-1">
          <li>No unlawful content, malware, or attempts to probe or overload the service.</li>
          <li>No uploading of others&apos; confidential documents without authority.</li>
          <li>No resale of output as regulated legal advice.</li>
        </ul>

        <h2 className="text-lg font-bold mt-8 mb-2">7. Intellectual property</h2>
        <p>
          You retain rights in documents you upload. We need a limited licence to process them to provide the
          service. Our branding, site and software remain ours.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">8. Liability</h2>
        <p>
          The service is provided &quot;as is&quot;. To the fullest extent permitted by law we exclude liability for
          loss of profit, contracts, data or indirect loss arising from use of the tool or reliance on its output.
          Nothing excludes liability for death or personal injury caused by negligence, fraud, or other liability that
          cannot be limited under English law. Our total liability for any claim is limited to the greater of £50 or
          the fees you paid us in the 3 months before the claim.
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">9. Report a problem</h2>
        <p>
          Copyright or other concerns:{" "}
          <a className="text-blue-600" href="mailto:tobyburrows1@icloud.com">
            tobyburrows1@icloud.com
          </a>
          .
        </p>

        <h2 className="text-lg font-bold mt-8 mb-2">10. Law</h2>
        <p>These terms are governed by the laws of England and Wales. Courts of England and Wales have jurisdiction.</p>
      </main>
    </div>
  );
}
